### ISSUE TITLE
add HTML <head> metadata

### ISSUE THREAD

**Issue by alifeee** [EkulRF/BestFilmsByCountry#6]
head is pretty empty

![image](https://github.com/EkulRF/BestFilmsByCountry/assets/13833017/13538dd3-70c0-472a-b98c-25b7486eb5c5)

It could have nice things like

- [x] tab title
- [x] favicon
- [ ] og metadata

For \<head\> template, see https://alifeee.co.uk/

**Comment by EkulRF** [comment]
favicon done

**Comment by alifeee** [comment]
> favicon done

neat :)

if you want to put it in the site you will want to put `<link rel="icon" href="/favicon.ico">` in the head (with the correct filename).

Example head from my website

```html
<head>
    <title>alifeee</title>
    <!-- meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- open graph meta -->
    <meta property="og:title" content="alifeee's website">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://alifeee.co.uk">
    <meta property="og:image" content="https://alifeee.co.uk/og-image.jpg">
    <meta property="og:description" content="My personal website. What horrors could lie within?">
    <meta property="og:locale" content="en_GB">

    <!-- favicon -->
    <link rel="icon" href="/favicon.ico">

    <!-- stylesheets & fonts -->
    <link rel="stylesheet" href="/stylesheet.css">
```

**Comment by alifeee** [comment]
you closed this issue but you did not add any of the metadata

![image](https://github.com/EkulRF/BestFilmsByCountry/assets/13833017/0441bf89-dff4-4137-a4d6-d2518ae769b5)

thank you for your time goodbye
